# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budgetid', models.BigIntegerField(unique=True)),
                ('budgetname', models.CharField(help_text=b'Budget name', max_length=255)),
                ('budgetamount', models.BigIntegerField()),
                ('budgetdeliverymethod', models.CharField(choices=[(b'STANDARD', b'Standard'), (b'ACCELERATED', b'Accelerated'), (b'TESTING', b'Testing')], max_length=20)),
                ('budgetstatus', models.CharField(choices=[(b'ENABLED', b'Enabled'), (b'PAUSED', b'Paused'), (b'REMOVED', b'Removed'), (b'TESTING', b'Testing')], max_length=20)),
                ('internalbudgetrefreshdate', models.DateTimeField(auto_now_add=True)),
                ('internalbudgetcreationdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
